// Catalan strings (G8). Keys as in strings-en.js; a missing key falls back to English.
export default {
  'menu.File': 'Fitxer', 'menu.Edit': 'Edita', 'menu.View': 'Visualitza', 'menu.Timeline': 'Línia de temps', 'menu.Generate': 'Genera', 'menu.Window': 'Finestra', 'menu.Help': 'Ajuda',
  'page.timeline': 'Línia de temps', 'page.assets': 'Recursos', 'page.review': 'Revisió', 'page.settings': 'Configuració', 'page.stage': 'Etapes',
  'sub.characters': 'Personatges', 'sub.locations': 'Localitzacions', 'sub.props': 'Atrezzo', 'sub.media': 'Mitjans', 'sub.clips': 'Clips',
  'sub.approvals': 'Aprovacions', 'sub.queue': 'Cua', 'sub.takes': 'Preses', 'sub.notes': 'Notes', 'sub.compare': 'Compara', 'sub.costs': 'Costos',
  'top.openNotes': 'notes obertes: {n}', 'top.noNotes': 'cap nota oberta',
  'stage.lyrics': 'Lletra', 'stage.script': 'Guió', 'stage.breakdown': 'Desglossament', 'stage.characters': 'Personatges', 'stage.scenery': 'Escenaris', 'stage.storyboard': 'Storyboard', 'stage.final': 'Final',
  'shown.empty': 'buida', 'shown.in_progress': 'en curs', 'shown.needs_you': 'et necessita', 'shown.ready': 'a punt per tancar', 'shown.done': 'feta', 'shown.changed': 'feta ⚠ ha canviat',
  'rail.next': 'següent:', 'rail.allDone': 'totes les etapes fetes', 'rail.round': 'Ronda {n}', 'rail.yourOpen': 'les teves notes obertes: {n}', 'rail.send': 'Envia la ronda a Claude',
  'rail.working': 'Claude hi treballa', 'rail.finished': 'Claude ha acabat', 'rail.close': 'Tanca la revisió {id}',
  'bar.markDone': '✓ Feta', 'bar.reopen': 'Reobre', 'bar.needsYou': 'Et necessita', 'bar.saveVersion': 'Desa la versió', 'bar.sendEdit': 'Envia l\'edició',
  'bar.ask': 'Demana a l\'agent…', 'bar.sendRound': 'Envia la ronda {n} ({k})', 'bar.roundWorking': 'Ronda {n}: Claude hi treballa', 'bar.closeRevision': 'Tanca la revisió {id}',
  'bar.list': 'Llista', 'bar.time': 'Temps', 'bar.nothingBlocking': 'res no ho bloqueja', 'bar.noAgent': 'cap agent connectat · Connecta Claude…',
  'dlg.close': 'tanca (Esc)', 'dlg.ok': 'D\'acord', 'dlg.cancel': 'Cancel·la', 'dlg.copy': 'copia', 'dlg.copied': 'copiat',
  'set.language': 'idioma', 'set.languageHint': 'els menús, les etapes, la barra d\'etapes, els botons i la benvinguda; la resta, de moment, en anglès',
  'set.generator': 'generador', 'set.costs': 'costos', 'set.project': 'projecte', 'set.view': 'visualització', 'set.columns': 'columnes', 'set.keybindings': 'dreceres de teclat',
  'set.paired': 'pàgines vinculades', 'set.pairedHint': 'pàgines d\'un altre origen (l\'aplicació allotjada) que poden arribar a aquest ordinador; per vincular-ne una: npx ai-videoclip-director pair',
  'set.pairedNone': 'cap pàgina vinculada', 'set.revoke': 'Revoca', 'set.revoked': '{id} revocada: aquella pàgina ja no pot arribar a aquest ordinador',
  'set.pairedCol': 'origen · abast · vinculada · darrer ús', 'set.scope.director': 'actua com tu (mai els fitxers privats)', 'set.scope.read': 'només lectura',
  'ob.title': 'Benvingut al Director Workbench',
  'ob.lead': 'Dirigeix un videoclip amb un assistent d\'IA: la cançó va de dalt a baix, i cada columna (lletra, guió, plans, preses, notes) comparteix el mateix temps.',
  'ob.start': 'Tres maneres de començar',
  'ob.song': 'Comença per una cançó', 'ob.songDo': 'Deixa-hi anar la cançó (mp3, wav, m4a…) i la lletra: la durada, el ritme i els temps de cada vers es llegeixen en aquest ordinador.',
  'ob.lyrics': 'Només la lletra', 'ob.lyricsDo': 'Enganxa el poema ara; la cançó, més endavant, quan la tinguis (etapa Lletra: Afegeix la cançó…).',
  'ob.demo': 'Obre la demo', 'ob.demoDo': 'Un projecte sintètic curt amb totes les etapes fetes: fes-hi un cop d\'ull abans de començar el teu.',
  'ob.connect': 'Connecta Claude', 'ob.connectDo': 'Qualsevol xat de Claude Code pot treballar en el mateix projecte a través del servidor MCP: veus cada canvi aquí, en directe.', 'ob.connectBtn': 'Connecta Claude…',
  'ob.data': 'On es guarden les dades', 'ob.dataDo': 'Cada projecte és una carpeta de fitxers normals en aquest ordinador. No en surt res si no aproves una generació de pagament.',
  'ob.dataUnknown': '(el servidor no ho ha dit: obre la pàgina des d\'aquest ordinador)',
  'ob.check': 'Aquest ordinador', 'ob.notNow': 'Ara no', 'ob.lang': 'Idioma',
  'ob.again': 'Ajuda › Benvinguda… ho torna a mostrar.',
  'chk.title': 'Comprovació del sistema', 'chk.server': 'Servidor del workbench', 'chk.serverOk': 'en marxa · v{v}', 'chk.serverDown': 'no respon',
  'chk.code': 'Codi', 'chk.codeOk': 'al dia', 'chk.codeStale': 'desfasat: reinicia el servidor',
  'chk.ffmpeg': 'ffmpeg / ffprobe', 'chk.ffmpegOk': 'trobat', 'chk.ffmpegNo': 'no trobat: cal per llegir una cançó, les ones, les miniatures i els fulls de contactes',
  'chk.ffmpegFix': 'Instal·la\'l i reinicia el workbench: Windows: winget install ffmpeg · macOS: brew install ffmpeg · Linux: sudo apt install ffmpeg',
  'chk.fal': 'clau de fal (generació de pagament)', 'chk.falOk': 'trobada ({src})', 'chk.falNo': 'no configurada: opcional. Sense clau, les peticions aprovades s\'executen com a "Obre en una altra aplicació" (un paquet de prompts, 0 $)',
  'chk.falFix': 'Per generar aquí: defineix FAL_KEY abans d\'arrencar el workbench, o fal_key_file a workbench.config.json (un fitxer fora del projecte). No enganxis mai la clau en un xat.',
  'chk.agent': 'Claude (MCP)', 'chk.agentOk': 'connectat: darrera escriptura {what}', 'chk.agentNo': 'cap agent no ha escrit des que s\'ha engegat el servidor',
  'chk.data': 'Carpeta de dades', 'chk.recheck': 'Torna a comprovar', 'chk.open': 'Comprovació del sistema…',
  'err.downTitle': 'El servidor del workbench no respon.', 'err.downDo': 'Torna a engegar-lo: npx ai-videoclip-director (o npm start a la carpeta del workbench). Aquesta pàgina es reconnecta sola.',
  'err.back': 'El servidor torna a respondre.', 'err.reload': 'Recarrega',
  'err.stale': 'Reinicia el servidor.', 'err.staleDo': 'El codi del workbench ha canviat al disc després d\'engegar-lo ({files}): aquesta pàgina podria demanar coses que encara no coneix. Reinicia\'l i recarrega.',
  'err.reloadPage': 'Recarrega la pàgina.', 'err.reloadDo': 'El servidor s\'ha reiniciat amb codi nou des que es va carregar aquesta pàgina.',
  'err.noFfmpeg': 'No s\'ha trobat ffmpeg.', 'err.noFfmpegDo': 'Cal per llegir una cançó, les ones i les miniatures.', 'err.how': 'Com s\'arregla…',
  'err.loadTitle': 'No s\'ha pogut carregar el projecte "{p}"', 'err.loadDo': 'El servidor del workbench està en marxa? Engega\'l (npx ai-videoclip-director, o npm start a la carpeta del workbench) i torna-ho a provar.',
  'err.retry': 'Torna-ho a provar', 'err.openDemo': 'Obre la demo',
  'help.welcome': 'Benvinguda… (comença aquí)', 'help.health': 'Comprovació del sistema…',
};
