// Spanish strings (G8). Keys as in strings-en.js; a missing key falls back to English.
export default {
  'menu.File': 'Archivo', 'menu.Edit': 'Edición', 'menu.View': 'Ver', 'menu.Timeline': 'Línea de tiempo', 'menu.Generate': 'Generar', 'menu.Window': 'Ventana', 'menu.Help': 'Ayuda',
  'page.timeline': 'Línea de tiempo', 'page.assets': 'Recursos', 'page.review': 'Revisión', 'page.settings': 'Ajustes', 'page.stage': 'Etapas',
  'sub.characters': 'Personajes', 'sub.locations': 'Localizaciones', 'sub.props': 'Atrezo', 'sub.media': 'Medios', 'sub.clips': 'Clips',
  'sub.approvals': 'Aprobaciones', 'sub.queue': 'Cola', 'sub.takes': 'Tomas', 'sub.notes': 'Notas', 'sub.compare': 'Comparar', 'sub.costs': 'Costes',
  'top.openNotes': 'notas abiertas: {n}', 'top.noNotes': 'ninguna nota abierta',
  'stage.lyrics': 'Letra', 'stage.script': 'Guion', 'stage.breakdown': 'Desglose', 'stage.characters': 'Personajes', 'stage.scenery': 'Escenarios', 'stage.storyboard': 'Storyboard', 'stage.final': 'Final',
  'shown.empty': 'vacía', 'shown.in_progress': 'en curso', 'shown.needs_you': 'te necesita', 'shown.ready': 'lista para cerrar', 'shown.done': 'hecha', 'shown.changed': 'hecha ⚠ ha cambiado',
  'rail.next': 'siguiente:', 'rail.allDone': 'todas las etapas hechas', 'rail.round': 'Ronda {n}', 'rail.yourOpen': 'tus notas abiertas: {n}', 'rail.send': 'Enviar la ronda a Claude',
  'rail.working': 'Claude está trabajando', 'rail.finished': 'Claude ha terminado', 'rail.close': 'Cerrar la revisión {id}',
  'bar.markDone': '✓ Hecha', 'bar.reopen': 'Reabrir', 'bar.needsYou': 'Te necesita', 'bar.saveVersion': 'Guardar versión', 'bar.sendEdit': 'Enviar edición',
  'bar.ask': 'Pedir al agente…', 'bar.sendRound': 'Enviar la ronda {n} ({k})', 'bar.roundWorking': 'Ronda {n}: Claude está trabajando', 'bar.closeRevision': 'Cerrar la revisión {id}',
  'bar.list': 'Lista', 'bar.time': 'Tiempo', 'bar.nothingBlocking': 'nada lo bloquea', 'bar.noAgent': 'ningún agente conectado · Conectar Claude…',
  'dlg.close': 'cerrar (Esc)', 'dlg.ok': 'Aceptar', 'dlg.cancel': 'Cancelar', 'dlg.copy': 'copiar', 'dlg.copied': 'copiado',
  'set.language': 'idioma', 'set.languageHint': 'los menús, las etapas, la barra de etapas, los botones y la bienvenida; el resto, de momento, en inglés',
  'set.generator': 'generador', 'set.costs': 'costes', 'set.project': 'proyecto', 'set.view': 'vista', 'set.columns': 'columnas', 'set.keybindings': 'atajos de teclado',
  'set.paired': 'páginas vinculadas', 'set.pairedHint': 'páginas de otro origen (la aplicación alojada) que pueden llegar a este ordenador; para vincular una: npx ai-videoclip-director pair',
  'set.pairedNone': 'ninguna página vinculada', 'set.revoke': 'Revocar', 'set.revoked': '{id} revocada: esa página ya no puede llegar a este ordenador',
  'set.pairedCol': 'origen · alcance · vinculada · último uso', 'set.scope.director': 'actúa como tú (nunca los archivos privados)', 'set.scope.read': 'solo lectura',
  'ob.title': 'Te damos la bienvenida al Director Workbench',
  'ob.lead': 'Dirige un videoclip con un asistente de IA: la canción va de arriba abajo, y cada columna (letra, guion, planos, tomas, notas) comparte el mismo tiempo.',
  'ob.start': 'Tres maneras de empezar',
  'ob.song': 'Empezar por una canción', 'ob.songDo': 'Suelta la canción (mp3, wav, m4a…) y su letra: la duración, los pulsos y los tiempos de cada verso se leen en este ordenador.',
  'ob.lyrics': 'Solo la letra', 'ob.lyricsDo': 'Pega el poema ahora; la canción, más adelante, cuando la tengas (etapa Letra: Añadir canción…).',
  'ob.demo': 'Abrir la demo', 'ob.demoDo': 'Un proyecto sintético corto con todas las etapas hechas: échale un vistazo antes de empezar el tuyo.',
  'ob.connect': 'Conectar Claude', 'ob.connectDo': 'Cualquier chat de Claude Code puede trabajar en el mismo proyecto a través del servidor MCP: ves cada cambio aquí, en directo.', 'ob.connectBtn': 'Conectar Claude…',
  'ob.data': 'Dónde se guardan los datos', 'ob.dataDo': 'Cada proyecto es una carpeta de archivos normales en este ordenador. No sale nada de él si no apruebas una generación de pago.',
  'ob.dataUnknown': '(el servidor no lo ha dicho: abre la página desde este ordenador)',
  'ob.check': 'Este ordenador', 'ob.notNow': 'Ahora no', 'ob.lang': 'Idioma',
  'ob.again': 'Ayuda › Bienvenida… lo vuelve a mostrar.',
  'chk.title': 'Comprobación del sistema', 'chk.server': 'Servidor del workbench', 'chk.serverOk': 'en marcha · v{v}', 'chk.serverDown': 'no responde',
  'chk.code': 'Código', 'chk.codeOk': 'al día', 'chk.codeStale': 'desfasado: reinicia el servidor',
  'chk.ffmpeg': 'ffmpeg / ffprobe', 'chk.ffmpegOk': 'encontrado', 'chk.ffmpegNo': 'no encontrado: hace falta para leer una canción, las ondas, las miniaturas y las hojas de contactos',
  'chk.ffmpegFix': 'Instálalo y reinicia el workbench: Windows: winget install ffmpeg · macOS: brew install ffmpeg · Linux: sudo apt install ffmpeg',
  'chk.fal': 'clave de fal (generación de pago)', 'chk.falOk': 'encontrada ({src})', 'chk.falNo': 'sin configurar: opcional. Sin clave, las peticiones aprobadas se ejecutan como "Abrir en otra aplicación" (un paquete de prompts, 0 $)',
  'chk.falFix': 'Para generar aquí: define FAL_KEY antes de arrancar el workbench, o fal_key_file en workbench.config.json (un archivo fuera del proyecto). Nunca pegues la clave en un chat.',
  'chk.agent': 'Claude (MCP)', 'chk.agentOk': 'conectado: última escritura {what}', 'chk.agentNo': 'ningún agente ha escrito desde que arrancó el servidor',
  'chk.data': 'Carpeta de datos', 'chk.recheck': 'Volver a comprobar', 'chk.open': 'Comprobación del sistema…',
  'err.downTitle': 'El servidor del workbench no responde.', 'err.downDo': 'Vuelve a arrancarlo: npx ai-videoclip-director (o npm start en la carpeta del workbench). Esta página se reconecta sola.',
  'err.back': 'El servidor vuelve a responder.', 'err.reload': 'Recargar',
  'err.stale': 'Reinicia el servidor.', 'err.staleDo': 'El código del workbench ha cambiado en disco después de arrancarlo ({files}): esta página podría pedir cosas que todavía no conoce. Reinícialo y recarga.',
  'err.reloadPage': 'Recarga la página.', 'err.reloadDo': 'El servidor se ha reiniciado con código nuevo desde que se cargó esta página.',
  'err.noFfmpeg': 'No se ha encontrado ffmpeg.', 'err.noFfmpegDo': 'Hace falta para leer una canción, las ondas y las miniaturas.', 'err.how': 'Cómo arreglarlo…',
  'err.loadTitle': 'No se ha podido cargar el proyecto "{p}"', 'err.loadDo': '¿Está en marcha el servidor del workbench? Arráncalo (npx ai-videoclip-director, o npm start en la carpeta del workbench) y vuelve a intentarlo.',
  'err.retry': 'Reintentar', 'err.openDemo': 'Abrir la demo',
  'help.welcome': 'Bienvenida… (empieza aquí)', 'help.health': 'Comprobación del sistema…',
};
